### ISSUE TITLE
totalitems with long type

### ISSUE THREAD

**Issue by KiarashS** [cloudscribe/cloudscribe.Web.Pagination#40]
Please add support for `totalitems` with `long` type.

**Comment by joeaudette** [comment]
That is a good idea, I will do that!
You must be paging through some really huge lists :-D

**Comment by KiarashS** [comment]
@joeaudette Thats right :-D

**Comment by joeaudette** [comment]
This is now implemented and new nuget packages have been published.
Thanks again for the good suggestion!

**Comment by KiarashS** [comment]
@joeaudette Thanks. You're too fast
