### ISSUE TITLE
ToPagedList performance on IQueryable implementation

### ISSUE THREAD

**Issue by vsopko** [cloudscribe/cloudscribe.Web.Pagination#42]
Test 1:
`var list = _context.Posts.ToPagedList(1, 10);`

Test 2:
`var list = _context.Posts.ToPagedList(1, 10,` **100**`);`

Both tests produces the same two sql queries: one for select and one for count. In second case It does not need to call internally IQueryable Count() because count value passed as param.

**Comment by joeaudette** [comment]
PagedList was marked as obsolete a long time ago and more recently it was removed from this project.
I never used it in any of my projects, it is not needed for PagerTagHelper.
