### ISSUE TITLE
Remove Next and Previous Links

### ISSUE THREAD

**Issue by QuotationMark** [cloudscribe/cloudscribe.Web.Pagination#45]
Hi Joe,

I have been using your pagination utility for sometime now and find it very useful. However, I am not a fan of the Next and Previous Links << and >> as they come and go depending on whether you are at the start or end of a set of pages.

I have looked at the code and would propose something along the following...

Add the following to PaginationSettings.cs
`public bool RemoveNextPrevLinks { get; set; } = false;`

Add to PageTagHelper.cs
`[HtmlAttributeName("cs-remove-nextprev-links")]`
`public bool RemoveNextPrevLinks { get; set; } = false;`

Add to PaginationLinkBuilder.cs
// Remove the PREV and NEXT Page Links
```
if (paginationSettings.RemoveNextPrevLinks)
{
    if (paginationLinks[0].Text == previousPageText) {
        paginationLinks.RemoveAt(0);
    }
    var lastLink = paginationLinks.Count - 1;
    if (paginationLinks[lastLink].Text == nextPageText) {
            paginationLinks.RemoveAt(lastLink);
    }
}
```

I have read your contribution notes and I think it best to leave you to respond!

Many Thanks
Mark Lawson
MarkNLawson@outlook.com

**Comment by joeaudette** [comment]
Hi Mark,

I've implemented this and published an updated nuget: https://www.nuget.org/packages/cloudscribe.Web.Pagination/2.1.9

Cheers,

Joe

**Comment by QuotationMark** [comment]
Thanks Joe
