### ISSUE TITLE
hashtag

### ISSUE THREAD

**Issue by SohailRB** [cloudscribe/cloudscribe.Web.Pagination#46]
Hi, if you added the hashtag to url, it would be great.
Thanks

**Comment by joeaudette** [comment]
Not enough information provided. In what context would hashtag be added? If you want to create menu items with hashtags can't you already do that in url?

**Comment by joeaudette** [comment]
Not enough information provided, what need is there for hashtag in pagination?

**Comment by VahidN** [comment]
I think "hashtag" here means the ability of having a URL history during Ajax navigation and also being able to reload an specific Ajax page by providing its URL such as localhost:5001/list **#page/1** using a library like [pathjs](https://github.com/mtrpcic/pathjs).  
[Here is an old sample about it](https://github.com/Kitsula/MvcAjaxPager/blob/master/MvcAjaxPager/jquery.pager-1.0.2.js).

**Comment by joeaudette** [comment]
I am open to a pull request.

**Comment by joeaudette** [comment]
Closing this as I have no plan or need to implement this. If someone else needs this and wants to implement I'm open to a pull request.
