### ISSUE TITLE
reconsider support preserve querystring for creating link

### ISSUE THREAD

**Issue by John0King** [cloudscribe/cloudscribe.Web.Pagination#47]
I previously create #25  to discuss this but it close very long ago.

In MVC , the **View** know nothing about the `Controller`, but the `Controller`  is the one who know about the Url stuff (querystring, route parameters). Back in `asp` or `aspx` age, dynamic build the link is very popular, but now with the routing system , it seems harder than the file base , and this library does  not preseve the querystring and only preseve current route value (implement by the default `UrlHelper` and underling routing system).
I think  preserve the querystring is more correct behaviour for a pagination compenent.
for example:
```
/public/movielist?tag=Marvel      
route: [controller=PublicController&action=Movielist]
query:   tag, sortby, classify

/vip/movieslist?sort=price&TodayUpdate=True  
route:[controller=VipController&action=Movielist]
query:  sort, TodayUpdate, PriceLower, PriceUpper

```

they use the same View with different ViewComponent/PartialView (the filter panel) , then It's hard to tell the `PageTagHelper` the right route values, but can be easily do by dynamic build the link .

on the other hand,  I just want to go to next page, it'll give me wrong data if the url missing a querystring.

https://github.com/John0King/cloudscribe.Web.Pagination/blob/1b32bd1f7680da40e796dd561612485468a5ba4a/src/cloudscribe.Web.Pagination/PagerTagHelper.cs#L424-L481

this is my fork of your library , the `AddCurrentQueryString` is what I add , but missing handle the `ActionDescriptor.RouteValues`  ( this is the values that the routing system use for handing controller/action selection , that they must not repeat in `RouteValueDictionarys ` (they will not generate querystring)  eg. `/home/index?area=top&Action=close` )

I suggest to add the `QueryString` and `RouteData.RouteValues` process , and a new `supress-auto-route` attribute to the PageTagHeper , the default value should be `false`  since it won't break any link that you current manual specify the `action` and `controller`

**Comment by joeaudette** [comment]
I have added the changes to preserve the ambient query string by default, it can be disabled by 

    cs-preserve-ambient-querystring="false"

new nuget published https://www.nuget.org/packages/cloudscribe.Web.Pagination/2.1.10

**Comment by John0King** [comment]
Thanks , I can use the official nuget package now 👍 .

**Comment by joeaudette** [comment]
Thanks for your suggested improvement!
