### ISSUE TITLE
Calling Javascript functions

### ISSUE THREAD

**Issue by ghronkrepps** [cloudscribe/cloudscribe.Web.Pagination#51]
Instead of calling an action on a controller, I'm looking to call Javascript functions on click of the numbers and passing the page number as a parameter to the function. Is this functionality possible?

The reason being is I want to post an entire form on the click of the pager buttons so my plan was to use a jquery ajax function to post it like this.

    function ChangePage(pageNumber)
    {
        $.ajax({
            type: 'POST',
            url: "/Items/ChangePage",
            data: $('#SearchForm').serialize(),
            success: function (result)
            {
                $('#target').html(result);
            }
        });
    }

Am I going about this the wrong way?

**Comment by joeaudette** [comment]
I don't have any ideas for your specific question as I wouldn't approach it like that.

What I do for ajax search forms with paging is use a form that uses ajax with get and I set the pager to use ajax and pass all the same form parameters as asp-route values

You can see an example in this modal partial which is itself loaded by ajax
https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.CompiledViews.Bootstrap4/Views/UserAdmin/UserLookupModal.cshtml

It has the div element whose contents will be replaced by ajax form search and or ajax paging, and inside that div is the partial view which has the actual form and pager.

https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.CompiledViews.Bootstrap4/Views/UserAdmin/UserModalGridPartial.cshtml

Hope that helps,

Joe

**Comment by joeaudette** [comment]
forgot to mention my approach depends on having jquery unobtrusive ajax script

    <script src="~/pathto/jquery.unobtrusive-ajax.min.js"></script>

**Comment by joeaudette** [comment]
There are some ajax examples in the paging demo app as well

**Comment by ghronkrepps** [comment]
My search form has like 25 parameters to send. Would you still recommend the same way?

**Comment by joeaudette** [comment]
the latest version of the pager actually captures/preserves all the query string parameters of the current request without having to specify them with asp-route-paramname. But that only works with GET requests and not sure if it works with ajax get requests. If it doesn't work with ajax then either specify all 25 or don't use ajax, then you don't have to specify them.

**Comment by ghronkrepps** [comment]
I'm using a get request like your example with ajax and it's working. I specified all of the parameters so the query string looks a bit crazy but it works. :)

Thanks for your help!
