### ISSUE TITLE
Can't use page for cs-pagenumber-param

### ISSUE THREAD

**Issue by Cyrus-Sushiant** [cloudscribe/cloudscribe.Web.Pagination#56]
Hi
Cloud please help me in razor page (.net core 3.1) when I want paging link with cs-psgenumber-param="page". It doesn't work, and instead of generate link just put # in anchor.

**Comment by CrispinF** [comment]
Hi @Cyrus-Sushiant can you show or link to your code? there's a typo in your text above, but maybe that's not really copied from your code?

**Comment by Cyrus-Sushiant** [comment]
you can change [that line](https://github.com/cloudscribe/cloudscribe.Web.Pagination/blob/b976500f4a0b05984cd86293033e5fabbea31f8d/src/PagingDemo.WebPages/Pages/Index.cshtml#L45) to this code

`<cs-pager cs-paging-pagenumber="@Model.List.PageNumber"
                  cs-paging-totalitems="@Model.List.TotalItems"
                  cs-paging-pagesize="@Model.List.PageSize"
                  cs-pagenumber-param="page"
                  asp-route-Page="/FakePage"
                  cs-pager-li-current-class="page-item active"
                  cs-pager-link-other-class="page-link"
                  cs-pager-link-current-class="page-link"></cs-pager>`

**Comment by CrispinF** [comment]
@Cyrus-Sushiant that is a demo of cloudscribe.Web.Pagination in a razor page, and you'll see a comment in the code explaining why not to use the name "page" for the paging parameter in this context: https://github.com/cloudscribe/cloudscribe.Web.Pagination/blob/b976500f4a0b05984cd86293033e5fabbea31f8d/src/PagingDemo.WebPages/Pages/Index.cshtml.cs#L20 
But other than that you can call the parameter whatever you like so long as everything matches up.
