### ISSUE TITLE
Please upgrade to .net 6

### ISSUE THREAD

**Issue by HolyOne** [cloudscribe/cloudscribe.Web.Pagination#60]
I have problems with this package in all my projects because it requires .net 5

**Comment by zulq** [comment]
You can use the current 5.0 package and do the following:
In your `Program.cs` add `builder.Services.AddCloudscribePagination();`.
And for handling bootstrap 5 add the following to your view:
` cs-pager-link-other-class="page-link"
cs-pager-li-other-class="page-item"
 cs-pager-link-current-class="page-link"` and modified the active item class as follows: ` cs-pager-li-current-class="page-item active"`

**Comment by HolyOne** [comment]
I can run it in .net6 but I have issues when I publish the project with the option "Enbale ReadyToRun Compilation".

If I select this option It also requires .net5 on the server because I used this component. Otherwise it will not run.

**Comment by simonech** [comment]
Any updates? NET 5 is out of support now.

**Comment by CrispinF** [comment]
@simonech @HolyOne @zulq this has been released for .NET 6. Hope this helps!
