### ISSUE TITLE
Bootstrap 5 support?

### ISSUE THREAD

**Issue by JGMelon22** [cloudscribe/cloudscribe.Web.Pagination#65]
Hello, there :wave: 
Any chances to include Bootstrap 5 support or to add at [docs](https://www.cloudscribe.com/cloudscribe-web-pagination) how to with this version?

**Comment by CrispinF** [comment]
@markidox to check whether already done, and review documentation page for anything needing update.

**Comment by CrispinF** [comment]
@JGMelon22 please note.

**Comment by JGMelon22** [comment]
You rock, gentlemen 🚀
![image](https://github.com/cloudscribe/cloudscribe.Web.Pagination/assets/73988556/19e9a7b4-5265-496f-b740-d7a9435ed7a5)
