### ISSUE TITLE
Test and fix demo Pagination web application

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.Web.Pagination#66]
On the docs page https://www.cloudscribe.com/cloudscribe-web-pagination we say 

> we have a demo web application that illustrates most of the available features including some ajax examples that show a loading indicator and show how to use the callbacks. In the demo the callbacks just log to the console in the web browser. 

We should test this is still working after upgrades to .NET and Bootstrap 5, and make any updates necessary.

**Comment by markidox** [comment]
All checked and looks like it's working fine.
